events {}

http {
    upstream django {
        server web:8000;
    }
    location = /healtz {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
    }

    server {
        listen 80;
        server_name app.doniyordev.uz;

        location /static/ {
            alias /app/staticfiles/;
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}