name: Deploy django app with Docker

on:
  push:
    branches:
      - main
      # - '.github/workflows/deploy-django-with-docker.yml'
      # - 'mydjangoapp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH key
        run: |
          echo "Key length: ${#SSH_KEY}"
          echo "First line: $(echo "$SSH_KEY" | head -1)"
          echo "Last line: $(echo "$SSH_KEY" | tail -1)"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./mydjangoapp
        run: |
          docker build -t registry.digitalocean.com/devops-course-registry/mydjangoapp:${{ github.sha }} .

      - name: Login to DigitalOcean Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u doniyortolibov2006@gmail.com --password-stdin

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/devops-course-registry/mydjangoapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "mydjangoapp/deploy/docker-compose.yaml"
          target: "/opt/mydjangoapp/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/mydjangoapp/

            echo "=== CONTENT AFTER MV ==="
            cat docker-compose.yaml

            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u doniyortolibov2006@gmail.com --password-stdin

            yq -i '.services.django.image = "registry.digitalocean.com/devops-course-registry/mydjangoapp:${{ github.sha }}"' docker-compose.yaml

            echo "=== CONTENT AFTER YQ ==="
            cat docker-compose.yaml

            docker compose pull
            docker compose up -d --remove-orphans